---
- name: Ensure Kubelet is enabled and started
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true
  become: true

- name: Initialize controller node
  ansible.builtin.shell: |
    kubeadm init --pod-network-cidr={{ pod_network_cidr }} --apiserver-advertise-address={{ ansible_default_ipv4.address }}
  args:
    creates: /etc/kubernetes/admin.conf
  become: true

- name: Create .kube directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    mode: '0755'

- name: Copy admin config to remote user and set the owner correctly
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: true
    mode: '0600'
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
  become: true

- name: Get helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4
    dest: /tmp/get_helm.sh
    mode: '0700'
  become: true

- name: Check if Helm is installed
  ansible.builtin.command: helm version
  ignore_errors: true
  changed_when: false
  register: helm_version

- name: Install helm
  ansible.builtin.command: /tmp/get_helm.sh
  become: true
  when: helm_version.rc != 0

- name: Get the cilium cli version
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
    return_content: true
  register: cilium_cli_version

- name: Unarchive the cilium install
  ansible.builtin.unarchive:
    src: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version.content | trim }}/cilium-linux-amd64.tar.gz"
    dest: /usr/local/bin
  args:
    creates: /usr/local/bin/cilium
  become: true

- name: Check if Cilium is installed
  ansible.builtin.command: cilium status
  ignore_errors: true
  changed_when: false
  register: cilium_status
  environment:
    KUBECONFIG: "{{ kubeconfig }}"

- name: Install Cilium
  ansible.builtin.command: cilium install
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  become: true
  when: cilium_status.rc != 0

- name: Check if flux is installed
  ansible.builtin.stat:
    path: /usr/local/bin/flux
  register: flux_binary

- name: Get the fluxcd version
  ansible.builtin.uri:
    url: https://api.github.com/repos/fluxcd/flux2/releases/latest
    return_content: true
  register: flux_version
  when: not flux_binary.stat.exists

- name: Unarchive the fluxcd install
  ansible.builtin.unarchive:
    src: "https://github.com/fluxcd/flux2/releases/download/{{ (flux_version.content | from_json).tag_name }}/flux_{{ (flux_version.content | from_json).tag_name | replace('v', '') }}_linux_amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: true
  when: not flux_binary.stat.exists
  become: true