---
- name: Get the cilium cli version
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
    return_content: true
  register: cilium_cli_version

- name: Unarchive the cilium install
  ansible.builtin.unarchive:
    src: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version.content | trim }}/cilium-linux-amd64.tar.gz"
    dest: /usr/local/bin
  args:
    creates: /usr/local/bin/cilium
  become: true

- name: Check if Cilium is installed
  ansible.builtin.command: cilium status
  ignore_errors: true
  changed_when: false
  register: cilium_status
  environment:
    KUBECONFIG: /home/flor/.kube/config

- name: Install Cilium
  ansible.builtin.command: cilium install
  environment:
    KUBECONFIG: /home/flor/.kube/config
  become: true
  when: cilium_status.rc != 0