---
- name: Get helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4
    dest: /tmp/get_helm.sh
    mode: '0700'
  become: true

- name: Check if Helm is installed
  ansible.builtin.command: helm version
  ignore_errors: true
  changed_when: false
  register: helm_version

- name: Install helm
  ansible.builtin.command: /tmp/get_helm.sh
  become: true
  when: helm_version.rc != 0

- name: Update helm repos
  ansible.builtin.command: helm repo update
  environment:
    KUBECONFIG: /home/flor/.kube/config
  changed_when: false
