- name: Allow the flor user to sudo all commands
  community.general.sudoers:
    name: allow-sudo
    state: present
    user: flor
    commands: ALL
  become: true

- name: Update & upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe
  become: true

- name: Install neofetch
  ansible.builtin.apt:
    name: neofetch
    state: present
  become: true

- name: Disable swap for current session
  command: swapoff -a
  become: true
  when: ansible_facts["swaptotal_mb"] > 0

- name: Disable swap permanently, persist reboots
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: yes
  become: true

- name: Kernel module for k8s networking & container storage
  community.general.modprobe:
    name: '{{ item }}'
    state: present
  loop:
    - br_netfilter
    - overlay
  become: true

- name: Configuring kernel modules
  ansible.posix.sysctl:
    name: '{{ item }}'
    state: present
    reload: true
    value: '1'
  loop:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
  become: true

- name: Configure module load.d to make it persistent for kubernetes
  ansible.builtin.copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/k8s.conf
  become: true

- name: Enable ufw
  community.general.ufw:
    state: enabled
  become: true

- name: allow routed ufw
  community.general.ufw:
    default: allow
    direction: "routed"
  become: true

- name: Allow tcp for ports from anywhere
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  become: true
  loop:
    - 22
    - 6443
    - 2379:2380
    - 10250
    - 10257
    - 10259
    - 30007

- name: Make sure Kubernetes uses internal IP instead of Tailscale ip
  ansible.builtin.lineinfile:
    path: /etc/default/kubelet
    regexp: '^\s*KUBELET_EXTRA_ARGS\s'
    line: KUBELET_EXTRA_ARGS=--node-ip={{ ansible_default_ipv4.address }}
  become: true
  notify: Restart kubelet service