---
- hosts: cluster
  roles:
    - role: common
      tags: common
    - role: tailscale
      tags: tailscale
    - role: containerd
      tags: containerd
    - role: kubernetes
      tags: kubernetes

- hosts: controllers
  roles:
    - role: controller_init
      tags: controller_init
    - role: cilium
      tags: cilium
    - role: cluster_addons
      tags: cluster_addons
  tasks:
    - name: Create kubeadm join token
      command: kubeadm token create --print-join-command
      register: join_command
      become: true
      tags: kubernetes

- hosts: workers
  tags: kubernetes
  tasks:
    - name: Join k8s cluster
      ansible.builtin.shell: |
        {{ hostvars['hpprodesk01'].join_command.stdout }}
      args:
        creates: /etc/kubernetes/kubelet.conf
      become: true
      tags: kubernetes

    - name: Label the nodes
      command: kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/worker=worker
      delegate_to: hpprodesk01
      become: false
      environment:
        KUBECONFIG: /home/flor/.kube/config
      tags: kubernetes